myApp/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as:'about'
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

myApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myApp/app/models/post.rb
class Post < ApplicationRecord
    validates :name, presence: true 
end

myApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

myApp/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about 
    end
    


end

myApp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post =Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create 
   # render plain: params[:post].inspect
    @post = Post.new(post_params)
    if(@post.save)
      redirect_to @post
    else 
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if(@post.update(post_params))
      redirect_to @post
    else 
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy 
    
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:name, :colour, :height )
    end

end

myApp/app/helpers/application_helper.rb
module ApplicationHelper
end

myApp/app/helpers/pages_helper.rb
module PagesHelper
end

myApp/app/helpers/posts_helper.rb
module PostsHelper
end

myApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-light bg-dark fixed-top">


  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
  
      <li class="nav-item active p-2">
         <%= link_to "List Minions" , home_path %> 
      </li>
      <li class="nav-item p-2">
         <%= link_to "Create Minions" , new_post_path %>
      </li>
     
    </ul>
  </div>
</nav>

<%= yield %>
  
  </body>
</html>

myApp/app/views/pages/about.html.erb
<h1> About me </h1>

myApp/app/views/posts/edit.html.erb
<h1> Edit Minion</h1>
  
<%= form_for :post, url: post_path(@post), method: :patch do |form| %>
 
  
    <p>
      <%= form.label :name %>
      <%= form.text_field :name %><br>


      <%= form.label :colour %>
      <%= form.text_field :colour %><br>

      <%= form.label :height %>
      <%= form.text_field :height %><br>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>

myApp/app/views/posts/index.html.erb
<h1> Blog Posts</h1>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Colour</th>
                <th>Height</th>
                <th>Delete</th>
                <th>Update</th>
                
                
            </tr>
        </thead>
      
        <tbody>
        <%= @posts.each do |post| %>
            <tr>
                <td><%=post.name %></td>
                <td> <%=post.colour %></td>
                <td><%=post.height %> </td>
                <td> <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <td><%= link_to "Edit", edit_post_path(post) %></td>
                
            </tr>
        <% end %>
         
     
        </tbody>
      </table>
    </div>
    
    

myApp/app/views/posts/new.html.erb
<h1> Add Post</h1>
  
<%= form_with scope: :post, local: true, url: posts_path do |form| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_message.each do |msg| %> 
      <div class="alert alert-danger"> <%= msg %>  </div>
    <% end %>
  <% end %>
  
    <p>
      <%= form.label :name %>
      <%= form.text_field :name %><br>


      <%= form.label :colour %>
      <%= form.text_field :colour %><br>

      <%= form.label :height %>
      <%= form.text_field :height %><br>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>

myApp/app/views/posts/show.html.erb
  <h1>Post Show</h1>
  <div style=" height=30px ; ">
    <p>
        <strong>Name </strong>
        <%= @post.name %>
        <br>

        <strong>Colour </strong>
        <%= @post.colour %>
        <br>

        <strong> Height</strong>
        <%= @post.height %>
        <br>

        
    </p>
</div>